vectortest_template: vectortest_template.cpp hke_vector_template.h
	clear
	g++ vectortest_template.cpp -o vectortest_template
	@echo Project vectortest_template successfully built!



vectortest: vectortest.cpp hke_vector.*
	clear
	g++ vectortest.cpp hke_vector.cpp -o vectortest
	@echo Project vectortest successfully built!




